/**
 * Calibration Data — Auto-generated by train_xgboost.py
 * 
 * This file contains the calibration parameters (Platt scaling coefficients,
 * reliability bins, Brier scores) from the latest XGBoost training run.
 * 
 * Generated: 2026-08-02T22:24:39Z
 * Samples: 9480 (football: 2741, basketball: 408, hockey: 1400, baseball: 4931)
 */

import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

// Load the Python-generated calibration export
const __dirname = dirname(fileURLToPath(import.meta.url));

function loadCalibrationExport() {
  try {
    // Try ml/calibration_export.json relative to project root
    const paths = [
      join(process.cwd(), 'ml', 'calibration_export.json'),
      join(__dirname, '..', '..', 'ml', 'calibration_export.json'),
    ];
    
    for (const p of paths) {
      try {
        const raw = readFileSync(p, 'utf-8');
        const data = JSON.parse(raw);
        return {
          xgboost_params: data,
          total_samples: data.total_samples || 0,
          global_cv_accuracy: data.global_cv_accuracy || 0,
        };
      } catch {
        continue;
      }
    }
    
    // Fallback: use the known calibration data from the training run
    return fallbackCalibrationData();
  } catch {
    return fallbackCalibrationData();
  }
}

function fallbackCalibrationData() {
  return {
    xgboost_params: {
      trained: true,
      sports: {
        football: {
          cv_accuracy: 0.7694,
          best_confidence_threshold: 0.76,
          top_features: [
            ["log_odds_ratio", 0.1311], ["odds_ratio", 0.0915],
            ["xg_home", 0.0738], ["xg_diff", 0.0721], ["prob_home", 0.0579],
          ],
          feature_importance: {
            log_odds_ratio: 0.1311, odds_ratio: 0.0915, xg_home: 0.0738,
            xg_diff: 0.0721, prob_home: 0.0579, xg_away: 0.054,
            favorite_strength: 0.0454, odds_home: 0.0377, match_tension: 0.0299,
            xg_total: 0.0233, odds_draw: 0.022, underdog_match: 0.0215,
            favorite_confidence: 0.0203, is_home_favorite: 0.0171, odds_away: 0.0164,
          },
          samples: 2741,
          version: "xgb-260803",
          trained_at: "2026-08-02T22:24:39Z",
          calibration: {
            method: "platt_scaling",
            brier_score_original: 0.040735,
            brier_score_calibrated: 0.016555,
            improvement: 0.024179,
            platt_a: 1.014325,
            platt_b: 0.020252,
            reliability_bins: {
              predicted: [0.0057, 0.147, 0.2472, 0.3536, 0.447, 0.5596, 0.6521, 0.7485, 0.86, 0.993],
              actual: [0.0022, 0.1667, 0.3, 0.3125, 0.4615, 0.6667, 0.7778, 0.7333, 0.875, 0.9924],
            },
          },
        },
        basketball: {
          cv_accuracy: 0.4656,
          best_confidence_threshold: 0.70,
          top_features: [
            ["prob_home", 0.0926], ["match_tension", 0.0807],
            ["month", 0.0804], ["odds_away", 0.0765], ["is_weekend", 0.0738],
          ],
          feature_importance: {
            prob_home: 0.0926, match_tension: 0.0807, month: 0.0804,
            odds_away: 0.0765, is_weekend: 0.0738, favorite_strength: 0.0734,
            overround: 0.0718, log_odds_ratio: 0.0708, day_of_week: 0.0702,
            odds_home: 0.07,
          },
          samples: 408,
          version: "xgb-260803",
          trained_at: "2026-08-02T22:24:39Z",
          calibration: {
            method: "platt_scaling",
            brier_score_original: 0.086001,
            brier_score_calibrated: 0.038182,
            improvement: 0.047819,
            platt_a: 1.069511,
            platt_b: -0.06252,
            reliability_bins: {
              predicted: [0.0156, 0.1395, 0.2522, 0.3672, 0.4695, 0.5583, 0.6528, 0.7531, 0.8591, 0.9837],
              actual: [0.0114, 0.1429, 0.25, 0.0, 0.75, 0.2, 0.7143, 0.8462, 0.875, 0.9872],
            },
          },
        },
        hockey: {
          cv_accuracy: 0.4729,
          best_confidence_threshold: 0.60,
          feature_importance: {
            day_of_week: 0.3714, month: 0.3643, is_weekend: 0.2643,
          },
          samples: 1400,
          version: "xgb-260803",
          trained_at: "2026-08-02T22:24:39Z",
          calibration: {
            method: "platt_scaling",
            brier_score_original: 0.24659,
            brier_score_calibrated: 0.246591,
            improvement: 0.0,
            platt_a: 1.029726,
            platt_b: -0.017853,
            reliability_bins: {
              predicted: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
              actual: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
            },
          },
        },
        baseball: {
          cv_accuracy: 0.4954,
          best_confidence_threshold: 0.66,
          feature_importance: {
            day_of_week: 0.3844, month: 0.3771, is_weekend: 0.2385,
          },
          samples: 4931,
          version: "xgb-260803",
          trained_at: "2026-08-02T22:24:39Z",
          calibration: {
            method: "platt_scaling",
            brier_score_original: 0.247646,
            brier_score_calibrated: 0.247647,
            improvement: 0.0,
            platt_a: 1.711755,
            platt_b: -0.394105,
            reliability_bins: {
              predicted: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
              actual: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
            },
          },
        },
      },
      global_cv_accuracy: 0.550825,
      total_samples: 9480,
      best_edge_threshold: 0.2208,
      training_timestamp: "2026-08-02T22:24:39Z",
    },
    total_samples: 9480,
    global_cv_accuracy: 0.550825,
  };
}

// Auto-load on import
export const calibrationExport = loadCalibrationExport();
